/** Languages shown in the rotating applicant assistant banner. */
export const LANGUAGES = [
  { code: "en", flag: "🇺🇸", native: "English", banner: "Ask me a question in any language" },
  { code: "es", flag: "🇲🇽", native: "Español", banner: "Hazme una pregunta en cualquier idioma" },
  { code: "pt", flag: "🇧🇷", native: "Português", banner: "Faça-me uma pergunta em qualquer idioma" },
  { code: "fr", flag: "🇨🇦", native: "Français", banner: "Posez-moi une question dans n'importe quelle langue" },
  { code: "ht", flag: "🇭🇹", native: "Kreyòl", banner: "Poze m yon kesyon nan nenpòt lang" },
  { code: "de", flag: "🇩🇪", native: "Deutsch", banner: "Stellen Sie mir eine Frage in jeder Sprache" },
  { code: "it", flag: "🇮🇹", native: "Italiano", banner: "Fammi una domanda in qualsiasi lingua" },
  { code: "nl", flag: "🇳🇱", native: "Nederlands", banner: "Stel mij een vraag in elke taal" },
  { code: "pl", flag: "🇵🇱", native: "Polski", banner: "Zadaj mi pytanie w dowolnym języku" },
  { code: "ru", flag: "🇷🇺", native: "Русский", banner: "Задайте мне вопрос на любом языке" },
  { code: "no", flag: "🇳🇴", native: "Norsk", banner: "Still meg et spørsmål på hvilket som helst språk" },
  { code: "da", flag: "🇩🇰", native: "Dansk", banner: "Stil mig et spørgsmål på ethvert sprog" },
  { code: "sv", flag: "🇸🇪", native: "Svenska", banner: "Ställ mig en fråga på vilket språk som helst" },
  { code: "tr", flag: "🇹🇷", native: "Türkçe", banner: "Bana herhangi bir dilde soru sorun" },
  { code: "ar", flag: "🇸🇦", native: "العربية", banner: "اسألني سؤالاً بأي لغة" },
  { code: "ur", flag: "🇵🇰", native: "اردو", banner: "کسی بھی زبان میں مجھ سے سوال پوچھیں" },
  { code: "hi", flag: "🇮🇳", native: "हिन्दी", banner: "किसी भी भाषा में मुझसे प्रश्न पूछें" },
  { code: "zh", flag: "🇨🇳", native: "中文", banner: "用任何语言问我一个问题" },
  { code: "ja", flag: "🇯🇵", native: "日本語", banner: "どんな言語でも質問してください" },
  { code: "ko", flag: "🇰🇷", native: "한국어", banner: "어떤 언어로든 질문해 주세요" },
  { code: "vi", flag: "🇻🇳", native: "Tiếng Việt", banner: "Hỏi tôi một câu hỏi bằng bất kỳ ngôn ngữ nào" },
  { code: "tl", flag: "🇵🇭", native: "Filipino", banner: "Magtanong sa akin sa anumang wika" },
  { code: "id", flag: "🇮🇩", native: "Indonesia", banner: "Tanyakan pertanyaan kepada saya dalam bahasa apa pun" },
  { code: "th", flag: "🇹🇭", native: "ภาษาไทย", banner: "ถามคำถามฉันในภาษาใดก็ได้" },
];
