export const LANGUAGE_LABEL_ROTATE_MS = 2000;

// "select your preferred language" in rotation order
export const PREFERRED_LANGUAGE_LABELS = [
  { code: "en", text: "Select your preferred language" },
  { code: "ur", text: "اپنی پسندیدہ زبان منتخب کریں" },
  { code: "ar", text: "اختر لغتك المفضلة" },
  { code: "fr", text: "Sélectionnez votre langue préférée" },
  { code: "it", text: "Seleziona la tua lingua preferita" },
  { code: "es", text: "Selecciona tu idioma preferido" },
  { code: "de", text: "Wählen Sie Ihre bevorzugte Sprache" },
  { code: "pt", text: "Selecione seu idioma preferido" },
  { code: "nl", text: "Selecteer je voorkeurstaal" },
  { code: "tr", text: "Tercih ettiğiniz dili seçin" },
  { code: "ru", text: "Выберите предпочитаемый язык" },
  { code: "uk", text: "Виберіть бажану мову" },
  { code: "pl", text: "Wybierz preferowany język" },
  { code: "hi", text: "अपनी पसंदीदा भाषा चुनें" },
  { code: "bn", text: "আপনার পছন্দের ভাষা নির্বাচন করুন" },
  { code: "pa", text: "ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ" },
  { code: "fa", text: "زبان دلخواه خود را انتخاب کنید" },
  { code: "he", text: "בחר את השפה המועדפת עליך" },
  { code: "zh", text: "选择您的首选语言" },
  { code: "ja", text: "ご希望の言語を選択してください" },
  { code: "ko", text: "선호하는 언어를 선택하세요" },
  { code: "vi", text: "Chọn ngôn ngữ ưa thích của bạn" },
  { code: "th", text: "เลือกภาษาที่คุณต้องการ" },
  { code: "id", text: "Pilih bahasa pilihan Anda" },
  { code: "ms", text: "Pilih bahasa pilihan anda" },
  { code: "tl", text: "Piliin ang iyong gustong wika" },
  { code: "sw", text: "Chagua lugha unayopendelea" },
  { code: "el", text: "Επιλέξτε τη γλώσσα που προτιμάτε" },
  { code: "sv", text: "Välj ditt föredragna språk" },
  { code: "ro", text: "Selectați limba preferată" },
];
