export const WIDGET_STRINGS = {
  en: {
    error: "Sorry, something went wrong",
    errorCouldnt: "Sorry, I wasn't able to do that",
    errorVerify: "Sorry, that verification code didn't work",
    errorSend: "Sorry, I couldn't send that",
    tryAgain: "Please try again.",
    keepOpenAck: "Great! I'll stay open and be here whenever you need me.",
    introClosing: "I'm here to help as needed.",
    revertFailed: "Sorry, the revert failed",
    formNotLoaded: "Sorry, I couldn't load the form details",
    fetchFailed: "Sorry, I couldn't fetch that page",
    brandingApplied: (url) =>
      `I've applied the branding from **${url}**. The colors, fonts, and logos have been pre-filled — feel free to ask me to adjust anything!`,
  },
  es: {
    error: "Lo siento, algo salió mal",
    errorCouldnt: "Lo siento, no pude hacer eso",
    errorVerify: "Lo siento, ese código de verificación no funcionó",
    errorSend: "Lo siento, no pude enviar eso",
    tryAgain: "Por favor, inténtalo de nuevo.",
    keepOpenAck: "¡Perfecto! Me quedaré abierto y estaré aquí cuando me necesites.",
    introClosing: "Estoy aquí para ayudar cuando lo necesites.",
    revertFailed: "Lo siento, no se pudo revertir la acción",
    formNotLoaded: "Lo siento, no pude cargar los detalles del formulario",
    fetchFailed: "Lo siento, no pude obtener esa página",
    brandingApplied: (url) =>
      `He aplicado el branding de **${url}**. Los colores, fuentes y logos han sido completados. ¡Puedes pedirme que ajuste lo que necesites!`,
  },
  fr: {
    error: "Désolé, quelque chose s'est mal passé",
    errorCouldnt: "Désolé, je n'ai pas pu faire cela",
    errorVerify: "Désolé, ce code de vérification ne fonctionne pas",
    errorSend: "Désolé, je n'ai pas pu envoyer cela",
    tryAgain: "Veuillez réessayer.",
    keepOpenAck: "Parfait ! Je reste ouvert et serai là quand vous aurez besoin de moi.",
    introClosing: "Je suis là pour aider si besoin.",
    revertFailed: "Désolé, l'annulation a échoué",
    formNotLoaded: "Désolé, je n'ai pas pu charger les détails du formulaire",
    fetchFailed: "Désolé, je n'ai pas pu récupérer cette page",
    brandingApplied: (url) =>
      `J'ai appliqué le branding de **${url}**. Les couleurs, polices et logos ont été pré-remplis — demandez-moi d'ajuster ce que vous souhaitez !`,
  },
  pt: {
    error: "Desculpe, algo deu errado",
    errorCouldnt: "Desculpe, não consegui fazer isso",
    errorVerify: "Desculpe, esse código de verificação não funcionou",
    errorSend: "Desculpe, não consegui enviar isso",
    tryAgain: "Por favor, tente novamente.",
    keepOpenAck: "Ótimo! Ficarei aberto e estarei aqui sempre que precisar de mim.",
    introClosing: "Estou aqui para ajudar quando necessário.",
    revertFailed: "Desculpe, a reversão falhou",
    formNotLoaded: "Desculpe, não consegui carregar os detalhes do formulário",
    fetchFailed: "Desculpe, não consegui buscar essa página",
    brandingApplied: (url) =>
      `Apliquei o branding de **${url}**. Cores, fontes e logotipos foram preenchidos — sinta-se à vontade para pedir ajustes!`,
  },
  zh: {
    error: "抱歉，出现了问题",
    errorCouldnt: "抱歉，无法完成该操作",
    errorVerify: "抱歉，该验证码无效",
    errorSend: "抱歉，无法发送",
    tryAgain: "请重试。",
    keepOpenAck: "太好了！我会一直在这里，随时为您提供帮助。",
    introClosing: "我随时准备提供帮助。",
    revertFailed: "抱歉，撤销操作失败",
    formNotLoaded: "抱歉，无法加载表单详情",
    fetchFailed: "抱歉，无法获取该页面",
    brandingApplied: (url) => `已应用 **${url}** 的品牌设置。颜色、字体和徽标已预填充——请随时告诉我需要调整的地方！`,
  },
  ar: {
    error: "عذراً، حدث خطأ ما",
    errorCouldnt: "عذراً، لم أتمكن من إتمام ذلك",
    errorVerify: "عذراً، رمز التحقق هذا لم يكن صحيحاً",
    errorSend: "عذراً، لم أتمكن من الإرسال",
    tryAgain: "يرجى المحاولة مرة أخرى.",
    keepOpenAck: "رائع! سأبقى مفتوحاً وسأكون هنا كلما احتجت إليّ.",
    introClosing: "أنا هنا للمساعدة عند الحاجة.",
    revertFailed: "عذراً، فشل التراجع عن الإجراء",
    formNotLoaded: "عذراً، لم أتمكن من تحميل تفاصيل النموذج",
    fetchFailed: "عذراً، لم أتمكن من جلب تلك الصفحة",
    brandingApplied: (url) =>
      `تم تطبيق العلامة التجارية من **${url}**. تم ملء الألوان والخطوط والشعارات — اطلب مني أي تعديلات!`,
  },
  de: {
    error: "Entschuldigung, etwas ist schiefgelaufen",
    errorCouldnt: "Entschuldigung, ich konnte das nicht abschließen",
    errorVerify: "Entschuldigung, dieser Bestätigungscode hat nicht funktioniert",
    errorSend: "Entschuldigung, ich konnte das nicht senden",
    tryAgain: "Bitte versuchen Sie es erneut.",
    keepOpenAck: "Toll! Ich bleibe geöffnet und bin immer für Sie da.",
    introClosing: "Ich bin bei Bedarf für Sie da.",
    revertFailed: "Entschuldigung, die Rückgängig-Aktion ist fehlgeschlagen",
    formNotLoaded: "Entschuldigung, ich konnte die Formulardetails nicht laden",
    fetchFailed: "Entschuldigung, ich konnte die Seite nicht abrufen",
    brandingApplied: (url) =>
      `Das Branding von **${url}** wurde angewendet. Farben, Schriften und Logos wurden vorausgefüllt — bitten Sie mich gerne um Anpassungen!`,
  },
  it: {
    error: "Spiacente, qualcosa è andato storto",
    errorCouldnt: "Spiacente, non sono riuscito a completare quella operazione",
    errorVerify: "Spiacente, quel codice di verifica non ha funzionato",
    errorSend: "Spiacente, non sono riuscito a inviare",
    tryAgain: "Per favore riprova.",
    keepOpenAck: "Ottimo! Rimarrò aperto e sarò qui quando avrai bisogno di me.",
    introClosing: "Sono qui per aiutare quando necessario.",
    revertFailed: "Spiacente, il ripristino è fallito",
    formNotLoaded: "Spiacente, non sono riuscito a caricare i dettagli del modulo",
    fetchFailed: "Spiacente, non sono riuscito a recuperare quella pagina",
    brandingApplied: (url) =>
      `Ho applicato il branding di **${url}**. Colori, font e loghi sono stati precompilati — chiedimi pure di apportare modifiche!`,
  },
  ko: {
    error: "죄송합니다, 문제가 발생했습니다",
    errorCouldnt: "죄송합니다, 작업을 완료할 수 없었습니다",
    errorVerify: "죄송합니다, 그 인증 코드가 작동하지 않았습니다",
    errorSend: "죄송합니다, 전송할 수 없었습니다",
    tryAgain: "다시 시도해 주세요.",
    keepOpenAck: "좋습니다! 계속 열려 있을게요, 필요하실 때마다 여기 있겠습니다.",
    introClosing: "필요하실 때 도움을 드리겠습니다.",
    revertFailed: "죄송합니다, 되돌리기에 실패했습니다",
    formNotLoaded: "죄송합니다, 양식 세부 정보를 불러올 수 없었습니다",
    fetchFailed: "죄송합니다, 해당 페이지를 가져올 수 없었습니다",
    brandingApplied: (url) =>
      `**${url}**의 브랜딩이 적용되었습니다. 색상, 폰트, 로고가 미리 채워졌습니다 — 조정이 필요하시면 말씀해 주세요!`,
  },
  ja: {
    error: "申し訳ありませんが、問題が発生しました",
    errorCouldnt: "申し訳ありませんが、その操作を完了できませんでした",
    errorVerify: "申し訳ありませんが、その確認コードは正しくありませんでした",
    errorSend: "申し訳ありませんが、送信できませんでした",
    tryAgain: "もう一度お試しください。",
    keepOpenAck: "素晴らしい！開いたままにして、必要なときにいつでもここにいます。",
    introClosing: "必要なときにいつでもお手伝いします。",
    revertFailed: "申し訳ありませんが、元に戻すことができませんでした",
    formNotLoaded: "申し訳ありませんが、フォームの詳細を読み込めませんでした",
    fetchFailed: "申し訳ありませんが、そのページを取得できませんでした",
    brandingApplied: (url) =>
      `**${url}**のブランディングを適用しました。色、フォント、ロゴが事前に入力されました — 調整が必要な場合はお知らせください！`,
  },
  vi: {
    error: "Xin lỗi, đã xảy ra lỗi",
    errorCouldnt: "Xin lỗi, tôi không thể thực hiện điều đó",
    errorVerify: "Xin lỗi, mã xác minh đó không hoạt động",
    errorSend: "Xin lỗi, tôi không thể gửi điều đó",
    tryAgain: "Vui lòng thử lại.",
    keepOpenAck: "Tuyệt vời! Tôi sẽ ở đây bất cứ khi nào bạn cần.",
    introClosing: "Tôi ở đây để giúp đỡ khi cần.",
    revertFailed: "Xin lỗi, việc hoàn tác thất bại",
    formNotLoaded: "Xin lỗi, tôi không thể tải chi tiết biểu mẫu",
    fetchFailed: "Xin lỗi, tôi không thể tải trang đó",
    brandingApplied: (url) =>
      `Đã áp dụng thương hiệu từ **${url}**. Màu sắc, phông chữ và biểu trưng đã được điền sẵn — hãy yêu cầu tôi điều chỉnh bất cứ điều gì!`,
  },
  hi: {
    error: "माफ़ करें, कुछ गलत हो गया",
    errorCouldnt: "माफ़ करें, मैं ऐसा नहीं कर सका",
    errorVerify: "माफ़ करें, वह सत्यापन कोड काम नहीं किया",
    errorSend: "माफ़ करें, मैं वह नहीं भेज सका",
    tryAgain: "कृपया पुनः प्रयास करें।",
    keepOpenAck: "बढ़िया! मैं खुला रहूँगा और जब भी आपको ज़रूरत होगी, यहाँ रहूँगा।",
    introClosing: "मैं आवश्यकता पड़ने पर सहायता करने के लिए यहाँ हूँ।",
    revertFailed: "माफ़ करें, वापस करने में विफल रहा",
    formNotLoaded: "माफ़ करें, मैं फ़ॉर्म विवरण लोड नहीं कर सका",
    fetchFailed: "माफ़ करें, मैं वह पेज प्राप्त नहीं कर सका",
    brandingApplied: (url) =>
      `**${url}** से ब्रांडिंग लागू की गई। रंग, फ़ॉन्ट और लोगो पहले से भरे गए हैं — कुछ भी समायोजित करने के लिए मुझसे पूछें!`,
  },
  ru: {
    error: "Извините, что-то пошло не так",
    errorCouldnt: "Извините, я не смог это выполнить",
    errorVerify: "Извините, этот код подтверждения не подошёл",
    errorSend: "Извините, не удалось отправить",
    tryAgain: "Пожалуйста, попробуйте снова.",
    keepOpenAck: "Отлично! Я останусь открытым и буду здесь, когда вам понадоблюсь.",
    introClosing: "Я здесь, чтобы помочь при необходимости.",
    revertFailed: "Извините, не удалось отменить действие",
    formNotLoaded: "Извините, не удалось загрузить детали формы",
    fetchFailed: "Извините, не удалось загрузить эту страницу",
    brandingApplied: (url) =>
      `Применён брендинг из **${url}**. Цвета, шрифты и логотипы заполнены — попросите меня внести любые изменения!`,
  },
  tl: {
    error: "Paumanhin, may naganap na mali",
    errorCouldnt: "Paumanhin, hindi ko nagawa iyon",
    errorVerify: "Paumanhin, hindi gumana ang code ng pagpapatunay",
    errorSend: "Paumanhin, hindi ko maipadala iyon",
    tryAgain: "Pakisubukan muli.",
    keepOpenAck: "Napakagaling! Mananatili akong bukas at nandito kapag kailangan mo ako.",
    introClosing: "Nandito ako para tumulong kung kinakailangan.",
    revertFailed: "Paumanhin, nabigo ang pag-undo",
    formNotLoaded: "Paumanhin, hindi ko ma-load ang mga detalye ng form",
    fetchFailed: "Paumanhin, hindi ko makuha ang pahinang iyon",
    brandingApplied: (url) =>
      `Inilapat ang branding mula sa **${url}**. Ang mga kulay, font, at logo ay na-pre-fill — humingi sa akin ng anumang ayusin!`,
  },
  ur: {
    error: "معذرت، کچھ غلط ہو گیا",
    errorCouldnt: "معذرت، میں یہ نہیں کر سکا",
    errorVerify: "معذرت، وہ تصدیقی کوڈ کام نہیں کیا",
    errorSend: "معذرت، میں یہ نہیں بھیج سکا",
    tryAgain: "براہ کرم دوبارہ کوشش کریں۔",
    keepOpenAck: "بہترین! میں کھلا رہوں گا اور جب بھی آپ کو ضرورت ہو یہاں ہوں گا۔",
    introClosing: "میں ضرورت پڑنے پر مدد کے لیے یہاں ہوں۔",
    revertFailed: "معذرت، واپس لینا ناکام رہا",
    formNotLoaded: "معذرت، فارم کی تفصیلات لوڈ نہیں ہو سکیں",
    fetchFailed: "معذرت، وہ صفحہ حاصل نہیں ہو سکا",
    brandingApplied: (url) =>
      `میں نے **${url}** سے برانڈنگ لاگو کر دی ہے۔ رنگ، فونٹس اور لوگوز بھر دیے گئے ہیں — کوئی تبدیلی چاہیں تو مجھ سے کہیں!`,
  },
  pl: {
    error: "Przepraszam, coś poszło nie tak",
    errorCouldnt: "Przepraszam, nie mogłem tego zrobić",
    errorVerify: "Przepraszam, ten kod weryfikacyjny nie zadziałał",
    errorSend: "Przepraszam, nie mogłem tego wysłać",
    tryAgain: "Proszę spróbować ponownie.",
    keepOpenAck: "Świetnie! Pozostanę otwarty i będę tutaj, kiedy mnie potrzebujesz.",
    introClosing: "Jestem tutaj, aby pomóc w razie potrzeby.",
    revertFailed: "Przepraszam, cofnięcie nie powiodło się",
    formNotLoaded: "Przepraszam, nie mogłem załadować szczegółów formularza",
    fetchFailed: "Przepraszam, nie mogłem pobrać tej strony",
    brandingApplied: (url) =>
      `Zastosowano branding z **${url}**. Kolory, czcionki i logo zostały wstępnie wypełnione — poproś mnie o wszelkie zmiany!`,
  },
};
