import {
  useCreateFormRuleMutation,
  useGetFormRuleFromAiMutation,
  useUpdateSingleFormRuleMutation,
} from "@/redux/apis/formApis";
import { useState } from "react";
import { FaSpinner } from "react-icons/fa";
import { toast } from "react-toastify";
import Button from "../shared/small/Button";
import { SelectInputType } from "../shared/small/DynamicField";
import TextField from "../shared/small/TextField";

// ─── Constants ───────────────────────────────────────────────────────────────
const CATEGORY_OPTIONS = [
  { label: "Alert", value: "alert" },
  { label: "Display", value: "display" },
];

// ─── Rule Fields Guide ────────────────────────────────────────────────────────────
const RULE_FIELDS_GUIDE = [
  { field: "prompt", description: "Instruction sent to AI to generate the rule logic." },
  {
    field: "handler",
    description: "JavaScript logic generated by AI. Runs in backend to evaluate the rule.",
  },
  { field: "formula", description: "Human-readable logic of the rule." },
  { field: "example", description: "Example showing how the rule works with sample input/output." },
  { field: "explanation", description: "Explanation of why this rule exists and what it detects." },
];
const CreateRuleModal = ({ formId, setModal, refetch }) => {
  const [showRuleFieldsGuide, setShowRuleFieldsGuide] = useState(false);
  const [prompt, setPrompt] = useState("");
  const [name, setName] = useState("");
  const [category, setCategory] = useState("");
  const [order, setOrder] = useState("");
  const [handler, setHandler] = useState("");
  const [formula, setFormula] = useState("");
  const [example, setExample] = useState("");
  const [explanation, setExplanation] = useState("");
  const [createRule, { isLoading: isCreatingRule }] = useCreateFormRuleMutation();
  const [getFormRuleFromAi, { isLoading: isGettingFormRuleFromAi }] = useGetFormRuleFromAiMutation();

  const createRuleHandler = async () => {
    try {
      if (!formId || !prompt || !name || !handler || !formula || !example || !explanation || !category || !order)
        return toast.error("Please fill all the fields");
      const data = { formId, prompt, name, category, handler, formula, example, explanation, order };
      const res = await createRule(data).unwrap();
      if (res?.success) {
        toast?.success(res?.message || "Rule created successfully");
        await refetch();
        setModal(false);
      }
    } catch (error) {
      console.error("Error creating rule:", error);
      toast.error(error?.data?.message || "Failed to create rule");
    }
  };

  const getFormRuleFromAiHandler = async () => {
    try {
      if (!formId || !prompt || !name || !category) return toast.error("Please fill all the fields");
      const res = await getFormRuleFromAi({ formId, prompt, name, category }).unwrap();
      console.log(res);
      if (res?.success) {
        setName(res?.data?.name);
        setHandler(res?.data?.handler);
        setFormula(res?.data?.formula);
        setExample(res?.data?.example);
        setExplanation(res?.data?.explanation);
        setOrder(res?.data?.order);
      }
    } catch (error) {
      console.error("Error getting form rule from ai:", error);
      toast.error(error?.data?.message || "Failed to get form rule from ai");
    }
  };
  return (
    <div className="flex items-center w-full justify-center p-4">
      <div className="flex w-full max-w-3xl flex-col gap-6">
        <h3 className="text-center text-2xl font-semibold text-gray-800">Create Rule</h3>
        <div className="flex flex-col gap-2 w-full">
          <TextField
            label="Rule Name:*"
            id="rule-name"
            placeholder="Enter rule name"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
          <SelectInputType
            field={{
              label: "Category",
              options: CATEGORY_OPTIONS,
              uniqueId: "category",
            }}
            onChange={(e) => setCategory(e.target.value)}
            form={{ category: { name: "category", value: category } }}
          />
          <TextField
            label="Prompt"
            id="prompt"
            type="textarea"
            placeholder="Enter prompt for rule creation"
            value={prompt}
            textAreaHeight="100px"
            onChange={(e) => setPrompt(e.target.value)}
          />

          <div className="flex justify-end  w-full items-end gap-2">
            <Button
              label={showRuleFieldsGuide ? "Hide Fields Guide" : "Preview Fields Guide"}
              variant="secondary"
              onClick={() => setShowRuleFieldsGuide((prev) => !prev)}
            />

            <Button
              label="Get Rule from AI"
              variant="primary"
              icon={isGettingFormRuleFromAi && FaSpinner}
              cnLeft="mr-2 w-4 h-4 animate-spin"
              onClick={getFormRuleFromAiHandler}
              disabled={isGettingFormRuleFromAi || !prompt || !name || !category}
            />
          </div>
          {showRuleFieldsGuide && (
            <div className="flex flex-col gap-3 mt-4 border border-gray-200 rounded-xl p-4 bg-[#FAFBFF]">
              <h4 className="text-lg font-semibold text-gray-800">Rule Fields Guide</h4>

              <div className="overflow-x-auto">
                <table className="w-full text-sm border border-gray-200 rounded-md overflow-hidden">
                  <thead className="bg-gray-100 text-gray-600">
                    <tr>
                      <th className="text-left px-3 py-2">Field</th>
                      <th className="text-left px-3 py-2">Description</th>
                    </tr>
                  </thead>
                  <tbody>
                    {RULE_FIELDS_GUIDE.map((item, index) => (
                      <tr key={index} className="border-t">
                        <td className="px-3 py-2 font-mono text-blue-600">{item.field}</td>
                        <td className="px-3 py-2 text-gray-700">{item.description}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <div className="text-xs text-gray-500">
                These fields are generated by AI and used to define how your rule works.
              </div>
            </div>
          )}
        </div>

        {formula && example && (
          <div className="flex flex-col gap-4 mt-4 border border-gray-200 rounded-xl p-4 bg-[#FAFBFF]">
            <h4 className="text-lg font-semibold text-gray-800">Rule Preview</h4>
            {explanation && (
              <div>
                <p className="text-sm font-medium text-gray-600 mb-1">Explanation</p>
                <div className="text-sm text-gray-800 bg-white border rounded-md p-3">{explanation}</div>
              </div>
            )}
            <div>
              <p className="text-sm font-medium text-gray-600 mb-1">Formula</p>
              <div className="text-sm font-mono text-blue-600 bg-white border rounded-md p-3 wrap-break-word">
                {formula}
              </div>
            </div>
            <div>
              <p className="text-sm font-medium text-gray-600 mb-1">Example Calculation</p>
              <pre className="text-sm text-gray-800 bg-white border rounded-md p-3 whitespace-pre-wrap">{example}</pre>
            </div>
            <details className="mt-2">
              <summary className="cursor-pointer text-sm text-gray-500">Show technical code</summary>
              <pre className="text-xs bg-black text-green-400 p-3 rounded-md mt-2 overflow-x-auto">{handler}</pre>
            </details>
          </div>
        )}
        <div className="flex w-full justify-end gap-2">
          <Button label="Cancel" variant="secondary" onClick={() => setModal(false)} />
          <Button
            label="Create Rule"
            variant="primary"
            icon={isCreatingRule && FaSpinner}
            cnLeft="mr-2 w-4 h-4 animate-spin"
            onClick={createRuleHandler}
            disabled={
              isCreatingRule ||
              !formId ||
              !prompt ||
              !name ||
              !handler ||
              !formula ||
              !example ||
              !explanation ||
              !category ||
              !order
            }
          />
        </div>
      </div>
    </div>
  );
};
const UpdateRuleModal = ({ ruleData, setModal, refetch }) => {
  const [showRuleFieldsGuide, setShowRuleFieldsGuide] = useState(false);
  const [prompt, setPrompt] = useState(ruleData?.prompt);
  const [name, setName] = useState(ruleData?.name);
  const [category, setCategory] = useState(ruleData?.category);
  const [handler, setHandler] = useState(ruleData?.handler);
  const [formula, setFormula] = useState(ruleData?.formula);
  const [example, setExample] = useState(ruleData?.example);
  const [explanation, setExplanation] = useState(ruleData?.explanation);
  const [order] = useState(ruleData?.order);
  const [updateRule, { isLoading: isUpdatingRule }] = useUpdateSingleFormRuleMutation();
  const [getFormRuleFromAi, { isLoading: isGettingFormRuleFromAi }] = useGetFormRuleFromAiMutation();

  const updateRuleHandler = async () => {
    try {
      if (!ruleData?._id || !prompt || !name || !handler || !formula || !example || !explanation || !category || !order)
        return toast.error("Please fill all the fields");

      const data = {
        formId: ruleData?.formId,
        prompt,
        name,
        category,
        handler,
        formula,
        example,
        explanation,
        order,
      };

      const res = await updateRule({ data, ruleId: ruleData?._id }).unwrap();
      if (res?.success) {
        toast?.success(res?.message || "Rule updated successfully");
        await refetch();
        setModal(false);
      }
    } catch (error) {
      console.error("Error updating rule:", error);
      toast.error(error?.data?.message || "Failed to update rule");
    }
  };

  const getFormRuleFromAiHandler = async () => {
    try {
      if (!ruleData?.formId || !prompt || !name || !category) return toast.error("Please fill all the fields");
      const res = await getFormRuleFromAi({
        formId: ruleData?.formId,
        prompt,
        name,
        category,
        order,
      }).unwrap();
      if (res?.success) {
        setName(res?.data?.name);
        setHandler(res?.data?.handler);
        setFormula(res?.data?.formula);
        setExample(res?.data?.example);
        setExplanation(res?.data?.explanation);
        setCategory(res?.data?.category);
      }
    } catch (error) {
      console.error("Error getting form rule from ai:", error);
      toast.error(error?.data?.message || "Failed to get form rule from ai");
    }
  };
  return (
    <div className="flex items-center justify-center p-4">
      <div className="flex w-full max-w-2xl flex-col gap-6">
        <h3 className="text-center text-2xl font-semibold text-gray-800">Update Rule</h3>
        <div className="flex flex-col gap-2 w-full">
          <TextField
            label="Rule Name:*"
            id="rule-name"
            placeholder="Enter rule name"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
          <SelectInputType
            field={{
              label: "Category",
              options: CATEGORY_OPTIONS,
              uniqueId: "category",
            }}
            onChange={(e) => setCategory(e.target.value)}
            form={{ category: { name: "category", value: category } }}
          />
          <TextField
            label="Prompt"
            id="prompt"
            type="textarea"
            placeholder="Enter prompt for rule creation"
            value={prompt}
            textAreaHeight="100px"
            onChange={(e) => setPrompt(e.target.value)}
          />

          <div className="flex justify-end  w-full items-end gap-2">
            <Button
              label={showRuleFieldsGuide ? "Hide Fields Guide" : "Preview Fields Guide"}
              variant="secondary"
              onClick={() => setShowRuleFieldsGuide((prev) => !prev)}
            />

            <Button
              label="Get Rule from AI"
              variant="primary"
              icon={isGettingFormRuleFromAi && FaSpinner}
              cnLeft="mr-2 w-4 h-4 animate-spin"
              onClick={getFormRuleFromAiHandler}
              disabled={isGettingFormRuleFromAi || !prompt || !name || !category}
            />
          </div>
          {showRuleFieldsGuide && (
            <div className="flex flex-col gap-3 mt-4 border border-gray-200 rounded-xl p-4 bg-[#FAFBFF]">
              <h4 className="text-lg font-semibold text-gray-800">Rule Fields Guide</h4>

              <div className="overflow-x-auto">
                <table className="w-full text-sm border border-gray-200 rounded-md overflow-hidden">
                  <thead className="bg-gray-100 text-gray-600">
                    <tr>
                      <th className="text-left px-3 py-2">Field</th>
                      <th className="text-left px-3 py-2">Description</th>
                    </tr>
                  </thead>
                  <tbody>
                    {RULE_FIELDS_GUIDE.map((item, index) => (
                      <tr key={index} className="border-t">
                        <td className="px-3 py-2 font-mono text-blue-600">{item.field}</td>
                        <td className="px-3 py-2 text-gray-700">{item.description}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <div className="text-xs text-gray-500">
                These fields are generated by AI and used to define how your rule works.
              </div>
            </div>
          )}
        </div>

        {formula && example && (
          <div className="flex flex-col gap-4 mt-4 border border-gray-200 rounded-xl p-4 bg-[#FAFBFF]">
            <h4 className="text-lg font-semibold text-gray-800">Rule Preview</h4>
            {explanation && (
              <div>
                <p className="text-sm font-medium text-gray-600 mb-1">Explanation</p>
                <div className="text-sm text-gray-800 bg-white border rounded-md p-3">{explanation}</div>
              </div>
            )}
            <div>
              <p className="text-sm font-medium text-gray-600 mb-1">Formula</p>
              <div className="text-sm font-mono text-blue-600 bg-white border rounded-md p-3 wrap-break-word">
                {formula}
              </div>
            </div>
            <div>
              <p className="text-sm font-medium text-gray-600 mb-1">Example Calculation</p>
              <pre className="text-sm text-gray-800 bg-white border rounded-md p-3 whitespace-pre-wrap">{example}</pre>
            </div>
            <details className="mt-2">
              <summary className="cursor-pointer text-sm text-gray-500">Show technical code</summary>
              <pre className="text-xs bg-black text-green-400 p-3 rounded-md mt-2 overflow-x-auto">{handler}</pre>
            </details>
          </div>
        )}
        <div className="flex w-full justify-end gap-2">
          <Button label="Cancel" variant="secondary" onClick={() => setModal(false)} />
          <Button
            label="Update Rule"
            variant="primary"
            icon={isUpdatingRule && FaSpinner}
            cnLeft="mr-2 w-4 h-4 animate-spin"
            onClick={updateRuleHandler}
            disabled={
              isUpdatingRule ||
              !ruleData?._id ||
              !prompt ||
              !name ||
              !handler ||
              !formula ||
              !example ||
              !explanation ||
              !category ||
              !order
            }
          />
        </div>
      </div>
    </div>
  );
};

export { CreateRuleModal, UpdateRuleModal };
