import { getTableStyles } from "@/data/data";
import { useBranding } from "@/hooks/BrandingContext";
import {
  useCreateFormRuleMutation,
  useDeleteSingleFormRuleMutation,
  useGetAllFormRulesQuery,
  useGetFormRuleFromAiMutation,
  useUpdateSingleFormRuleMutation,
  useUpdateStatusSingleFormRuleMutation,
} from "@/redux/apis/formApis";
import { MoreVertical, PencilIcon, PlusIcon, ToggleRight, Trash } from "lucide-react";
import React, { useMemo, useRef, useState } from "react";
import DataTable from "react-data-table-component";
import { FaSpinner } from "react-icons/fa";
import { useParams } from "react-router-dom";
import { toast } from "react-toastify";
import ConfirmationModal from "../shared/ConfirmationModal";
import Button from "../shared/small/Button";
import CustomLoading from "../shared/small/CustomLoading";
import Modal from "../shared/small/Modal";
import TextField from "../shared/small/TextField";
import { ThreeDotEditViewDelete } from "../shared/ThreeDotViewEditDelete";
import { SelectInputType } from "../shared/small/DynamicField";
import { IoMdPersonAdd } from "react-icons/io";

const CATEGORY_OPTIONS = [
  { label: "Alert", value: "alert" },
  { label: "Display", value: "display" },
];

const STATUS_OPTIONS = [
  { label: "Active", value: "active" },
  { label: "Inactive", value: "inactive" },
];

const RULE_FIELDS_GUIDE = [
  {
    field: "prompt",
    description: "Instruction sent to AI to generate the rule logic.",
  },
  {
    field: "handler",
    description: "JavaScript logic generated by AI. This runs in backend to evaluate the rule.",
  },
  {
    field: "formula",
    description: "Human-readable logic of the rule. Helps understand how the rule works.",
  },
  {
    field: "example",
    description: "Example showing how the rule works with sample input and output.",
  },
  {
    field: "explanation",
    description: "Explanation of why this rule exists and what it detects or validates.",
  },
];
const manageRulesColumns = () => [
  {
    name: "Rule Id",
    sortable: true,
    width: "100px",
    cell: (row) => (
      <span title={row?._id} className="text-textPrimary truncate text-sm">
        {row?._id}
      </span>
    ),
  },
  {
    name: "Rule Name",
    sortable: true,
    cell: (row) => <span className="text-textPrimary font-semibold capitalize">{row?.name}</span>,
    width: "200px",
  },
  {
    name: "Rule Prompt",
    sortable: true,
    cell: (row) => (
      <textarea
        value={row?.prompt}
        readOnly
        className="text-textPrimary border-frameColor w-full resize-none rounded-md border bg-[#FAFBFF] p-2 text-sm"
        rows={2}
      />
    ),
    grow: 2,
    wrap: true,
  },
  // {
  //   name: "Rule Priority",
  //   sortable: true,
  //   width: "150px",
  //   cell: (row) => (
  //     <span
  //       className={`px-4 py-2 w-25 text-center rounded-sm font-semibold capitalize text-white ${row?.priority === 0 ? "bg-green-500!" : row?.priority === 1 ? "bg-yellow-500!" : "bg-red-500!"}`}
  //     >
  //       {row?.priority === 0 ? "Low" : row?.priority === 1 ? "Medium" : "High"}
  //     </span>
  //   ),
  // },
  {
    name: "Category",
    sortable: true,
    width: "150px",
    cell: (row) => <span className="font-semibold">{row?.category}</span>,
  },
  {
    name: "Status",
    width: "120px",
    sortable: true,
    cell: (row) => <span className="font-semibold capitalize">{row?.isActive ? "Active" : "Inactive"}</span>,
  },
];

const ManageRules = () => {
  const formId = useParams().formId;
  const actionMenuRefs = useRef(new Map());
  const [actionMenu, setActionMenu] = useState(null);
  const [openCreateRuleModal, setOpenCreateRuleModal] = useState(false);
  const [selectedRow, setSelectedRow] = useState(null);
  const [deleteRuleConfirmation, setDeleteRuleConfirmation] = useState(null);
  const [updateStatusRuleConfirmation, setUpdateStatusRuleConfirmation] = useState(null);
  const [updateRuleConfirmation, setUpdateRuleConfirmation] = useState(null);
  const { primaryColor, textColor, backgroundColor, secondaryColor } = useBranding();
  const [filters, setFilters] = useState({
    name: "",
    category: "",
    status: "",
  });
  const tableStyles = getTableStyles({ primaryColor, secondaryColor, textColor, backgroundColor });

  const { data: rules, isLoading, refetch } = useGetAllFormRulesQuery({ formId });
  const [deleteRule, { isLoading: isDeletingRule }] = useDeleteSingleFormRuleMutation();
  const [updateStatusRule, { isLoading: isUpdatingStatusRule }] = useUpdateStatusSingleFormRuleMutation();

  const filteredRules = useMemo(() => {
    let data = rules?.data || [];
    return data.filter((rule) => {
      // Name filter
      const matchName = !filters.name || rule.name?.toLowerCase().includes(filters.name.toLowerCase());
      // Category filter
      const matchCategory = !filters.category || rule.category === filters.category;
      // Status filter
      const matchStatus =
        !filters.status ||
        (filters.status === "active" && rule.isActive) ||
        (filters.status === "inactive" && !rule.isActive);
      // Date filter
      return matchName && matchCategory && matchStatus;
    });
  }, [rules, filters]);

  const handleDeleteRule = async (ruleId) => {
    try {
      const res = await deleteRule({ ruleId }).unwrap();
      if (res?.success) {
        toast?.success(res?.message || "Rule deleted successfully");
        await refetch();
        setDeleteRuleConfirmation(null);
      }
    } catch (error) {
      console.error("Error deleting rule:", error);
      toast.error(error?.data?.message || "Failed to delete rule");
    }
  };
  const handleUpdateStatusRule = async (ruleId, isActive) => {
    try {
      const res = await updateStatusRule({ ruleId, isActive: !isActive }).unwrap();
      if (res?.success) {
        toast?.success(res?.message || "Rule status updated successfully");
        await refetch();
        setUpdateStatusRuleConfirmation(null);
      }
    } catch (error) {
      console.error("Error updating status rule:", error);
      toast.error(error?.data?.message || "Failed to update status rule");
    }
  };

  const ButtonsForThreeDot = useMemo(
    () => [
      {
        name: "Update Status",
        icon: <ToggleRight size={16} className="mr-2" />,
        onClick: (row) => {
          setSelectedRow(row);
          setActionMenu(null);
          setUpdateStatusRuleConfirmation(true);
        },
      },
      {
        name: "Update Rule",
        icon: <PencilIcon size={16} className="mr-2" />,
        onClick: (row) => {
          setSelectedRow(row);
          setActionMenu(null);
          setUpdateRuleConfirmation(true);
        },
      },
      {
        name: "Delete",
        icon: <Trash size={16} className="mr-2" />,
        onClick: (row) => {
          setSelectedRow(row);
          setActionMenu(null);
          setDeleteRuleConfirmation(true);
        },
      },
    ],
    [],
  );

  const columns = useMemo(
    () => [
      ...manageRulesColumns(),
      {
        name: "Action",
        width: "100px",
        cell: (row) => {
          if (!actionMenuRefs.current.has(row?._id)) {
            actionMenuRefs.current.set(row?._id, React.createRef());
          }
          const rowRef = actionMenuRefs.current.get(row?._id);

          return (
            <div className="relative" ref={rowRef}>
              <button
                onClick={() => setActionMenu((prevActionMenu) => (prevActionMenu === row?._id ? null : row?._id))}
                className="cursor-pointer rounded p-1 hover:bg-gray-100"
                aria-label="Actions"
              >
                <MoreVertical size={18} />
              </button>
              {actionMenu === row._id && <ThreeDotEditViewDelete buttons={ButtonsForThreeDot} row={row} />}
            </div>
          );
        },
      },
    ],
    [ButtonsForThreeDot, actionMenu],
  );
  if (isLoading) return <CustomLoading />;
  return (
    <>
      {openCreateRuleModal && (
        <Modal onClose={() => setOpenCreateRuleModal(false)}>
          <CreateRuleModal formId={formId} setModal={setOpenCreateRuleModal} refetch={refetch} />
        </Modal>
      )}
      {updateRuleConfirmation && (
        <Modal onClose={() => setUpdateRuleConfirmation(false)}>
          <UpdateRuleModal ruleData={selectedRow} setModal={setUpdateRuleConfirmation} refetch={refetch} />
        </Modal>
      )}

      <ConfirmationModal
        isOpen={!!deleteRuleConfirmation}
        onClose={() => setDeleteRuleConfirmation(null)}
        onConfirm={() => handleDeleteRule(selectedRow?._id)}
        title="Delete Rule"
        message={`Are you sure you want to delete this rule?`}
        isLoading={isDeletingRule}
        confirmButtonText="Delete"
        confirmButtonClassName="bg-red-500 text-white"
      />

      <ConfirmationModal
        isOpen={!!updateStatusRuleConfirmation}
        onClose={() => setUpdateStatusRuleConfirmation(null)}
        onConfirm={() => handleUpdateStatusRule(selectedRow?._id, selectedRow?.isActive)}
        isLoading={isUpdatingStatusRule}
        title="Update Status Rule"
        message={`Are you sure you want to update the status of this rule?`}
        confirmButtonText="Update"
        confirmButtonClassName="bg-red-500 text-white"
      />
      <div className="flex items-center justify-center p-4">
        <div className="flex w-full flex-col gap-6">
          {/* Filter  */}
          <div className="w-full bg-white border border-gray-200 rounded-xl p-4 shadow-sm">
            <div className="flex flex-col gap-4">
              <div className="flex flex-row justify-between items-center gap-4">
                <h3 className="text-textPrimary text-lg font-semibold">Manage Rules</h3>
              </div>
              {/* Top row */}
              <div className="flex flex-col md:flex-row gap-4 w-full">
                {/* Search */}
                <div className="flex flex-col w-full md:w-1/3">
                  <label className="text-xs text-gray-500 mb-1">Search</label>
                  <TextField
                    id="search-name"
                    placeholder="Search by rule name..."
                    value={filters.name}
                    onChange={(e) => setFilters({ ...filters, name: e.target.value })}
                  />
                </div>
                {/* Category */}
                <div className="flex flex-col w-full md:w-1/4">
                  <label className="text-xs text-gray-500 mb-1">Category</label>
                  <SelectInputType
                    field={{
                      options: CATEGORY_OPTIONS,
                      uniqueId: "category",
                    }}
                    onChange={(e) => setFilters({ ...filters, category: e.target.value })}
                    form={{ category: { name: "category", value: filters.category } }}
                  />
                </div>
                {/* Status */}
                <div className="flex flex-col w-full md:w-1/4">
                  <label className="text-xs text-gray-500 mb-1">Status</label>
                  <SelectInputType
                    field={{
                      options: STATUS_OPTIONS,
                      uniqueId: "status",
                    }}
                    onChange={(e) => setFilters({ ...filters, status: e.target.value })}
                    form={{ status: { name: "status", value: filters.status } }}
                  />
                </div>
                <div className="flex  justify-end items-end">
                  <Button
                    icon={PlusIcon}
                    className="w-40 h-13 rounded-lg"
                    label="Create Rule"
                    variant="primary"
                    onClick={() => setOpenCreateRuleModal(true)}
                  />
                </div>
              </div>
            </div>
          </div>

          <div className="w-full max-w-full ">
            <DataTable
              data={filteredRules || []}
              columns={columns}
              customStyles={tableStyles}
              pagination
              highlightOnHover
              progressPending={false}
              noDataComponent="No Rules found"
              className="rounded-t-xl!"
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default ManageRules;

const CreateRuleModal = ({ formId, setModal, refetch }) => {
  const [showRuleFieldsGuide, setShowRuleFieldsGuide] = useState(false);
  const [prompt, setPrompt] = useState("");
  const [name, setName] = useState("");
  const [category, setCategory] = useState("");
  const [handler, setHandler] = useState("");
  const [formula, setFormula] = useState("");
  const [example, setExample] = useState("");
  const [explanation, setExplanation] = useState("");
  const [createRule, { isLoading: isCreatingRule }] = useCreateFormRuleMutation();
  const [getFormRuleFromAi, { isLoading: isGettingFormRuleFromAi }] = useGetFormRuleFromAiMutation();

  const createRuleHandler = async () => {
    try {
      if (!formId || !prompt || !name || !handler || !formula || !example || !explanation || !category)
        return toast.error("Please fill all the fields");
      const data = { formId, prompt, name, category, handler, formula, example, explanation };
      const res = await createRule(data).unwrap();
      if (res?.success) {
        toast?.success(res?.message || "Rule created successfully");
        await refetch();
        setModal(false);
      }
    } catch (error) {
      console.error("Error creating rule:", error);
      toast.error(error?.data?.message || "Failed to create rule");
    }
  };

  const getFormRuleFromAiHandler = async () => {
    try {
      if (!formId || !prompt || !name || !category) return toast.error("Please fill all the fields");
      const res = await getFormRuleFromAi({ formId, prompt, name, category }).unwrap();
      if (res?.success) {
        setName(res?.data?.name);
        setHandler(res?.data?.handler);
        setFormula(res?.data?.formula);
        setExample(res?.data?.example);
        setExplanation(res?.data?.explanation);
      }
    } catch (error) {
      console.error("Error getting form rule from ai:", error);
      toast.error(error?.data?.message || "Failed to get form rule from ai");
    }
  };
  return (
    <div className="flex items-center w-full justify-center p-4">
      <div className="flex w-full max-w-3xl flex-col gap-6">
        <h3 className="text-center text-2xl font-semibold text-gray-800">Create Rule</h3>
        <div className="flex flex-col gap-2 w-full">
          <TextField
            label="Rule Name:*"
            id="rule-name"
            placeholder="Enter rule name"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
          <SelectInputType
            field={{
              label: "Category",
              options: CATEGORY_OPTIONS,
              uniqueId: "category",
            }}
            onChange={(e) => setCategory(e.target.value)}
            form={{ category: { name: "category", value: category } }}
          />
          <TextField
            label="Prompt"
            id="prompt"
            type="textarea"
            placeholder="Enter prompt for rule creation"
            value={prompt}
            textAreaHeight="100px"
            onChange={(e) => setPrompt(e.target.value)}
          />

          <div className="flex justify-end  w-full items-end gap-2">
            <Button
              label={showRuleFieldsGuide ? "Hide Fields Guide" : "Preview Fields Guide"}
              variant="secondary"
              onClick={() => setShowRuleFieldsGuide((prev) => !prev)}
            />

            <Button
              label="Get Rule from AI"
              variant="primary"
              icon={isGettingFormRuleFromAi && FaSpinner}
              cnLeft="mr-2 w-4 h-4 animate-spin"
              onClick={getFormRuleFromAiHandler}
              disabled={isGettingFormRuleFromAi || !prompt || !name || !category}
            />
          </div>
          {showRuleFieldsGuide && (
            <div className="flex flex-col gap-3 mt-4 border border-gray-200 rounded-xl p-4 bg-[#FAFBFF]">
              <h4 className="text-lg font-semibold text-gray-800">Rule Fields Guide</h4>

              <div className="overflow-x-auto">
                <table className="w-full text-sm border border-gray-200 rounded-md overflow-hidden">
                  <thead className="bg-gray-100 text-gray-600">
                    <tr>
                      <th className="text-left px-3 py-2">Field</th>
                      <th className="text-left px-3 py-2">Description</th>
                    </tr>
                  </thead>
                  <tbody>
                    {RULE_FIELDS_GUIDE.map((item, index) => (
                      <tr key={index} className="border-t">
                        <td className="px-3 py-2 font-mono text-blue-600">{item.field}</td>
                        <td className="px-3 py-2 text-gray-700">{item.description}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <div className="text-xs text-gray-500">
                These fields are generated by AI and used to define how your rule works.
              </div>
            </div>
          )}
        </div>

        {formula && example && (
          <div className="flex flex-col gap-4 mt-4 border border-gray-200 rounded-xl p-4 bg-[#FAFBFF]">
            <h4 className="text-lg font-semibold text-gray-800">Rule Preview</h4>
            {explanation && (
              <div>
                <p className="text-sm font-medium text-gray-600 mb-1">Explanation</p>
                <div className="text-sm text-gray-800 bg-white border rounded-md p-3">{explanation}</div>
              </div>
            )}
            <div>
              <p className="text-sm font-medium text-gray-600 mb-1">Formula</p>
              <div className="text-sm font-mono text-blue-600 bg-white border rounded-md p-3 wrap-break-word">
                {formula}
              </div>
            </div>
            <div>
              <p className="text-sm font-medium text-gray-600 mb-1">Example Calculation</p>
              <pre className="text-sm text-gray-800 bg-white border rounded-md p-3 whitespace-pre-wrap">{example}</pre>
            </div>
            <details className="mt-2">
              <summary className="cursor-pointer text-sm text-gray-500">Show technical code</summary>
              <pre className="text-xs bg-black text-green-400 p-3 rounded-md mt-2 overflow-x-auto">{handler}</pre>
            </details>
          </div>
        )}
        <div className="flex w-full justify-end gap-2">
          <Button label="Cancel" variant="secondary" onClick={() => setModal(false)} />
          <Button
            label="Create Rule"
            variant="primary"
            icon={isCreatingRule && FaSpinner}
            cnLeft="mr-2 w-4 h-4 animate-spin"
            onClick={createRuleHandler}
            disabled={
              isCreatingRule ||
              !formId ||
              !prompt ||
              !name ||
              !handler ||
              !formula ||
              !example ||
              !explanation ||
              !category
            }
          />
        </div>
      </div>
    </div>
  );
};
const UpdateRuleModal = ({ ruleData, setModal, refetch }) => {
  const [showRuleFieldsGuide, setShowRuleFieldsGuide] = useState(false);
  const [prompt, setPrompt] = useState(ruleData?.prompt);
  const [name, setName] = useState(ruleData?.name);
  const [category, setCategory] = useState(ruleData?.category);
  const [handler, setHandler] = useState(ruleData?.handler);
  const [formula, setFormula] = useState(ruleData?.formula);
  const [example, setExample] = useState(ruleData?.example);
  const [explanation, setExplanation] = useState(ruleData?.explanation);
  const [updateRule, { isLoading: isUpdatingRule }] = useUpdateSingleFormRuleMutation();
  const [getFormRuleFromAi, { isLoading: isGettingFormRuleFromAi }] = useGetFormRuleFromAiMutation();

  const updateRuleHandler = async () => {
    try {
      if (!ruleData?._id || !prompt || !name || !handler || !formula || !example || !explanation || !category)
        return toast.error("Please fill all the fields");

      const data = {
        formId: ruleData?.formId,
        prompt,
        name,
        category,
        handler,
        formula,
        example,
        explanation,
      };

      const res = await updateRule({ data, ruleId: ruleData?._id }).unwrap();
      if (res?.success) {
        toast?.success(res?.message || "Rule updated successfully");
        await refetch();
        setModal(false);
      }
    } catch (error) {
      console.error("Error updating rule:", error);
      toast.error(error?.data?.message || "Failed to update rule");
    }
  };

  const getFormRuleFromAiHandler = async () => {
    try {
      if (!ruleData?.formId || !prompt || !name || !category) return toast.error("Please fill all the fields");
      const res = await getFormRuleFromAi({ formId: ruleData?.formId, prompt, name, category }).unwrap();
      if (res?.success) {
        setName(res?.data?.name);
        setHandler(res?.data?.handler);
        setFormula(res?.data?.formula);
        setExample(res?.data?.example);
        setExplanation(res?.data?.explanation);
        setCategory(res?.data?.category);
      }
    } catch (error) {
      console.error("Error getting form rule from ai:", error);
      toast.error(error?.data?.message || "Failed to get form rule from ai");
    }
  };
  return (
    <div className="flex items-center justify-center p-4">
      <div className="flex w-full max-w-2xl flex-col gap-6">
        <h3 className="text-center text-2xl font-semibold text-gray-800">Update Rule</h3>
        <div className="flex flex-col gap-2 w-full">
          <TextField
            label="Rule Name:*"
            id="rule-name"
            placeholder="Enter rule name"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
          <SelectInputType
            field={{
              label: "Category",
              options: CATEGORY_OPTIONS,
              uniqueId: "category",
            }}
            onChange={(e) => setCategory(e.target.value)}
            form={{ category: { name: "category", value: category } }}
          />
          <TextField
            label="Prompt"
            id="prompt"
            type="textarea"
            placeholder="Enter prompt for rule creation"
            value={prompt}
            textAreaHeight="100px"
            onChange={(e) => setPrompt(e.target.value)}
          />

          <div className="flex justify-end  w-full items-end gap-2">
            <Button
              label={showRuleFieldsGuide ? "Hide Fields Guide" : "Preview Fields Guide"}
              variant="secondary"
              onClick={() => setShowRuleFieldsGuide((prev) => !prev)}
            />

            <Button
              label="Get Rule from AI"
              variant="primary"
              icon={isGettingFormRuleFromAi && FaSpinner}
              cnLeft="mr-2 w-4 h-4 animate-spin"
              onClick={getFormRuleFromAiHandler}
              disabled={isGettingFormRuleFromAi || !prompt || !name || !category}
            />
          </div>
          {showRuleFieldsGuide && (
            <div className="flex flex-col gap-3 mt-4 border border-gray-200 rounded-xl p-4 bg-[#FAFBFF]">
              <h4 className="text-lg font-semibold text-gray-800">Rule Fields Guide</h4>

              <div className="overflow-x-auto">
                <table className="w-full text-sm border border-gray-200 rounded-md overflow-hidden">
                  <thead className="bg-gray-100 text-gray-600">
                    <tr>
                      <th className="text-left px-3 py-2">Field</th>
                      <th className="text-left px-3 py-2">Description</th>
                    </tr>
                  </thead>
                  <tbody>
                    {RULE_FIELDS_GUIDE.map((item, index) => (
                      <tr key={index} className="border-t">
                        <td className="px-3 py-2 font-mono text-blue-600">{item.field}</td>
                        <td className="px-3 py-2 text-gray-700">{item.description}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <div className="text-xs text-gray-500">
                These fields are generated by AI and used to define how your rule works.
              </div>
            </div>
          )}
        </div>

        {formula && example && (
          <div className="flex flex-col gap-4 mt-4 border border-gray-200 rounded-xl p-4 bg-[#FAFBFF]">
            <h4 className="text-lg font-semibold text-gray-800">Rule Preview</h4>
            {explanation && (
              <div>
                <p className="text-sm font-medium text-gray-600 mb-1">Explanation</p>
                <div className="text-sm text-gray-800 bg-white border rounded-md p-3">{explanation}</div>
              </div>
            )}
            <div>
              <p className="text-sm font-medium text-gray-600 mb-1">Formula</p>
              <div className="text-sm font-mono text-blue-600 bg-white border rounded-md p-3 wrap-break-word">
                {formula}
              </div>
            </div>
            <div>
              <p className="text-sm font-medium text-gray-600 mb-1">Example Calculation</p>
              <pre className="text-sm text-gray-800 bg-white border rounded-md p-3 whitespace-pre-wrap">{example}</pre>
            </div>
            <details className="mt-2">
              <summary className="cursor-pointer text-sm text-gray-500">Show technical code</summary>
              <pre className="text-xs bg-black text-green-400 p-3 rounded-md mt-2 overflow-x-auto">{handler}</pre>
            </details>
          </div>
        )}
        <div className="flex w-full justify-end gap-2">
          <Button label="Cancel" variant="secondary" onClick={() => setModal(false)} />
          <Button
            label="Update Rule"
            variant="primary"
            icon={isUpdatingRule && FaSpinner}
            cnLeft="mr-2 w-4 h-4 animate-spin"
            onClick={updateRuleHandler}
            disabled={
              isUpdatingRule ||
              !ruleData?._id ||
              !prompt ||
              !name ||
              !handler ||
              !formula ||
              !example ||
              !explanation ||
              !category
            }
          />
        </div>
      </div>
    </div>
  );
};
