// city suggestions for the ID details form
export const MAJOR_CITIES = [
  // US Major Cities
  "New York City",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Jacksonville",
  "Fort Worth",
  "Columbus",
  "Charlotte",
  "Indianapolis",
  "San Francisco",
  "Seattle",
  "Denver",
  "Nashville",
  "Oklahoma City",
  "El Paso",
  "Washington DC",
  "Boston",
  "Las Vegas",
  "Memphis",
  "Louisville",
  "Portland",
  "Baltimore",
  "Milwaukee",
  "Albuquerque",
  "Tucson",
  "Fresno",
  "Sacramento",
  "Mesa",
  "Kansas City",
  "Atlanta",
  "Omaha",
  "Colorado Springs",
  "Raleigh",
  "Long Beach",
  "Virginia Beach",
  "Minneapolis",
  "Tampa",
  "New Orleans",
  "Arlington",
  "Wichita",
  "Bakersfield",
  "Aurora",
  "Anaheim",
  "Santa Ana",
  "Corpus Christi",
  "Riverside",
  "St. Louis",
  "Lexington",
  "Pittsburgh",
  "Stockton",
  "Anchorage",
  "Cincinnati",
  "St. Paul",
  "Greensboro",
  "Toledo",
  "Newark",
  "Plano",
  "Henderson",
  "Orlando",
  "Lincoln",
  "Jersey City",
  "Chandler",
  "St. Petersburg",
  "Laredo",
  "Norfolk",
  "Madison",
  "Durham",
  "Lubbock",
  "Winston-Salem",
  "Garland",
  "Glendale",
  "Hialeah",
  "Reno",
  "Baton Rouge",
  "Irvine",
  "Chesapeake",
  "Irving",
  "Scottsdale",
  "North Las Vegas",
  "Fremont",
  "Gilbert",
  "San Bernardino",
  "Birmingham",
  "Rochester",
  "Richmond",
  "Spokane",
  "Des Moines",
  "Montgomery",
  "Modesto",
  "Fayetteville",
  "Tacoma",
  "Shreveport",
  "Akron",
  "Yonkers",
  "Oxnard",
  "Fontana",
  "Augusta",
  "Mobile",
  "Little Rock",
  "Moreno Valley",
  "Amarillo",
  "Huntington Beach",
  "Grand Rapids",
  "Salt Lake City",
  "Tallahassee",
  "Huntsville",
  "Worcester",
  "Knoxville",
  "Brownsville",
  "Santa Clarita",
  "Providence",
  "Garden Grove",
  "Oceanside",
  "Fort Lauderdale",
  "Chattanooga",
  "Tempe",
  "Cape Coral",
  "Eugene",
  "Peoria",
  "Cary",
  "Springfield",
  "Fort Wayne",
  "Sioux Falls",
  "Pembroke Pines",
  "Elk Grove",
  "Vancouver",
  "Corona",
  "Hollywood",
  "Hayward",
  "Clarksville",
  "Paterson",
  "Murfreesboro",
  "Macon",
  "Lakewood",
  "Killeen",
  "Syracuse",
  "Salinas",
  "Pomona",
  "Escondido",
  "Sunnyvale",
  "Rockford",
  "Torrance",
  "Bridgeport",
  "Alexandria",
  "Savannah",
  "Roseville",
  "Surprise",
  "Pasadena",
  "Mesquite",
  "Gainesville",
  "Fullerton",
  "McAllen",
  "Thornton",
  "Olathe",
  "West Valley City",
  "Warren",
  "Hampton",
  "Dayton",
  "Columbia",
  "Sterling Heights",
  "Waco",
  "Cedar Rapids",
  "Elizabeth",
  "Denton",
  "Miramar",
  "Thousand Oaks",
  "Visalia",
  "Topeka",
  "Coral Springs",
  "Stamford",
  "Concord",
  "Hartford",
  "Simi Valley",
  "Lafayette",
  "Kent",
  "Santa Rosa",
  "El Monte",
  "Rancho Cucamonga",
  "Ontario",
  "San Buenaventura",
  "Fort Collins",
  "Jackson",
  "Honolulu",
  "Boise",
  "Billings",
  "Fargo",
  "Manchester",
  "San Juan",
  // Canadian Major Cities
  "Toronto",
  "Montreal",
  "Calgary",
  "Edmonton",
  "Ottawa",
  "Winnipeg",
  "Quebec City",
  "Hamilton",
  "Kitchener",
  "London",
  "Victoria",
  "Halifax",
  "Oshawa",
  "Windsor",
  "Saskatoon",
  "Regina",
  "St. Catharines",
  "Barrie",
  "Kelowna",
  "Abbotsford",
  "Sudbury",
  "Kingston",
  "Saguenay",
  "Trois-Rivières",
  "Guelph",
  "Moncton",
  "Brantford",
  "Saint John",
  "Thunder Bay",
  "Sherbrooke",
  "Nanaimo",
  "Fredericton",
  "Charlottetown",
  "Lethbridge",
  "Red Deer",
  "Kamloops",
  "Chilliwack",
  "Prince George",
  // UK Major Cities
  "Glasgow",
  "Liverpool",
  "Leeds",
  "Sheffield",
  "Edinburgh",
  "Bristol",
  "Leicester",
  "Coventry",
  "Bradford",
  "Cardiff",
  "Belfast",
  "Nottingham",
  "Kingston upon Hull",
  "Newcastle upon Tyne",
  "Stoke-on-Trent",
  "Southampton",
  "Derby",
  "Portsmouth",
  "Brighton",
  "Plymouth",
  "Wolverhampton",
  "Oxford",
  "Cambridge",
  "Norwich",
  "Swansea",
  "Aberdeen",
  "Dundee",
  "Inverness",
  "Exeter",
  "Gloucester",
  "Bath",
  "York",
  "Chester",
  // Australian Major Cities
  "Sydney",
  "Melbourne",
  "Brisbane",
  "Perth",
  "Adelaide",
  "Gold Coast",
  "Canberra",
  "Newcastle",
  "Wollongong",
  "Logan City",
  "Geelong",
  "Hobart",
  "Townsville",
  "Cairns",
  "Darwin",
  "Toowoomba",
  "Ballarat",
  "Bendigo",
  "Launceston",
  "Mackay",
  "Rockhampton",
  "Bunbury",
  "Bundaberg",
  "Hervey Bay",
];

export const ID_TYPE_SUGGESTIONS = ["Driver's License", "State ID", "Passport"];
