export const STORAGE_KEYS = {
  BRANDING_DATA: "brandingData",
};

export const SOCKET_EVENTS = {
  CONNECT: "connect",
  REGISTER_USER: "register_user",
};

export const AI_ASSISTANT_MODES = {
  SERVICE_PROVIDER: "service-provider",
  APPLICANT: "applicant",
};

export const FIELD_TYPES = {
  TEXT: "text",
  DATE: "date",
  EMAIL: "email",
  NUMBER: "number",
  PASSWORD: "password",
  TEXTAREA: "textarea",
  RANGE: "range",
  FILE: "file",
  RADIO: "radio",
  SELECT: "select",
  CHECKBOX: "checkbox",
  MULTI_CHECKBOX: "multi-checkbox",
};

export const formKeys = {
  beneficial_owners_key: "beneficial_information", // beneficial owners section key which is section for form
  additional_owners_hidden_section_key: "additional_owners_information", // additional owners info section key which is hidden section
  company_lookup_data: "company_lookup_data", // company lookup data section key
};

export const formFieldsStaticKeys = {
  additional_owners_key: "additional_owners", //static key for additional owners field which is inside beneficial owners page
};

export const additionalOwnersFields = {
  name: "",
  email: "",
  role: "",
  job_title: "",
  have_detail: "",
  phone: "",
  ssn: "",
  address: "",
  percentage: "",
  date_of_birth: "",
  id_number: "",
  id_type: "",
  id_issuer: "",
  id_issuer_date: "",
  isCompleted: false,
};

export const STATE_SUGGESTIONS = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
  "District of Columbia",
  "Puerto Rico",
  "Alberta",
  "British Columbia",
  "Manitoba",
  "New Brunswick",
  "Newfoundland and Labrador",
  "Northwest Territories",
  "Nova Scotia",
  "Nunavut",
  "Ontario",
  "Prince Edward Island",
  "Quebec",
  "Saskatchewan",
  "Yukon",
  "England",
  "Scotland",
  "Wales",
  "Northern Ireland",
  "New South Wales",
  "Victoria",
  "Queensland",
  "Western Australia",
  "South Australia",
  "Tasmania",
  "Australian Capital Territory",
  "Northern Territory",
];
